version: '3'
services:
  web:
    image: nextjs:latest
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=development
      - DB_CONNECTION=sqlite
      - DATABASE_URL=sqlite:///db.sqlite

  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db_data:/data

volumes:
  db_data: {}